
fun_getDBConn()
{
    if [ "$1" == "CRM" ]
    then
      DBCONN="system/lanchong@CRMP64"
#      echo ... $DBCONN
    elif [ "$1" == "JOTPP" ]
    then
      DBCONN="system/cal618@JOTPP"
#      echo ... $DBCONN
    else
      echo not correct DB!
      #exit 1
    fi
}

### MAIN ###
# problem tables are generated by vSyncDataChk.sh into /tmp/VSYNC/DDLMOD.lst
# ! for simplicity, assume $SCH.$TBL is unique in the whole replication.
TBLLIST=/tmp/VSYNC/DDLMOD.lst
TIDFILE=/tmp/VSYNC/TBLID.tobeResynced

DB=""
DBCONN=""
SCH=$2
TBL=$3

# iterate through the list:
cat $TBLLIST | while read l
do
  DBCONN=""
  DB=`echo $l|cut -d'|' -f1`
  SSCH=`echo $l|cut -d'|' -f2`
  TBL=`echo $l|cut -d'|' -f3`
  # 0: get ${DBCONN}
  fun_getDBConn $DB
  #echo $DB $SSCH $TBL $DBCONN
  # 1: reset curr_state=0 for the table, and disable the triggers
  /home/jenadmin/vSync/jobs/stpTbl.sh $DBCONN $SSCH $TBL
  # 2: truncate target table
  # for convenience, did it in vSyncDataChk.sh
  # 3: re-sync the table
  tblID=`grep -v ^$ $TIDFILE|tr -dc '0-9'`
  echo "to re-sync $tblID: $SSCH $TBL of $DB"
  /home/jenadmin/vSync/SQL/initTbl.sh $tblID
  > $TIDFILE
done

# clean up /tmp/VSYNC/DDLMOD.lst, which is populated by vSyncDataChk.sh
> $TBLLIST
